// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApNoepPEnZ5XjBvX66TkS2vHYOBSJsv6s',
    appId: '1:940954824449:web:bcaca9bba2225caf2af500',
    messagingSenderId: '940954824449',
    projectId: 'my-finance-per',
    authDomain: 'my-finance-per.firebaseapp.com',
    storageBucket: 'my-finance-per.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU4bnsKg7c73TcNvzuGYjsdoOgSYxMO1w',
    appId: '1:940954824449:android:20ac6f766d4110202af500',
    messagingSenderId: '940954824449',
    projectId: 'my-finance-per',
    storageBucket: 'my-finance-per.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo2xS6X-XA1qnTMDuGnP8M0KEZ1FN4fXc',
    appId: '1:940954824449:ios:8b482cbad0ac6c912af500',
    messagingSenderId: '940954824449',
    projectId: 'my-finance-per',
    storageBucket: 'my-finance-per.firebasestorage.app',
    iosBundleId: 'com.example.personalFinance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo2xS6X-XA1qnTMDuGnP8M0KEZ1FN4fXc',
    appId: '1:940954824449:ios:8b482cbad0ac6c912af500',
    messagingSenderId: '940954824449',
    projectId: 'my-finance-per',
    storageBucket: 'my-finance-per.firebasestorage.app',
    iosBundleId: 'com.example.personalFinance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyApNoepPEnZ5XjBvX66TkS2vHYOBSJsv6s',
    appId: '1:940954824449:web:435faae561d3569b2af500',
    messagingSenderId: '940954824449',
    projectId: 'my-finance-per',
    authDomain: 'my-finance-per.firebaseapp.com',
    storageBucket: 'my-finance-per.firebasestorage.app',
  );
}
